=== Esheen/ASP.NET-XML-project/PampersDiaper/pampers.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.w3schools.com"
xmlns="http://www.w3schools.com"
elementFormDefault="qualified">
  <xs:complexType name="CustomerType">
    <xs:attribute name="CustomerID"
       type="xs:int"
       use="required"/>
    <xs:attribute name="Fname"
       type="xs:string"
       use="required"/>
    <xs:attribute name="Lname"
       type="xs:string"
       use="required"/>
    <xs:attribute name="St1"
       type="xs:string"
       use="required"/>
    <xs:attribute name="City"
       type="xs:string"
       use="required"/>
    <xs:attribute name="State"
       type="xs:string"
       use="required"/>
  </xs:complexType>
  <xs:complexType name="ProductType">
    <xs:sequence>
      <xs:element name="Customer"
       maxOccurs="unbounded" type="CustomerType"/>
    </xs:sequence>
    <xs:attribute name="ProductID"
       type="xs:int" use="required"/>
    <xs:attribute name="ProductName"
       type="xs:string" use="required"/>
    <xs:attribute name="Size"
       type="xs:int" use="required"/>
    <xs:attribute name="Price"
       type="xs:int" use="required"/>
  </xs:complexType>
  <xs:complexType name="XOrderType">
    <xs:sequence>
      <xs:element name="Product"
       maxOccurs="unbounded" type="ProductType"/>
    </xs:sequence>
    <xs:attribute name="date"
       type="xs:date" use="required"/>
  </xs:complexType>
  <xs:element name="XOrder"
  type="XOrderType" />
</xs:schema>

=== Esheen/ASP.NET-XML-project/PampersDiaper/pampers.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="pampers.xslt"?>
<XOrder date="2016-10-06"
        xmlns="http://www.w3schools.com"
        xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation= "http://www.w3schools.com pampers.xsd">
  <Product ProductID="1" ProductName="Swaddlers" Size="1" Price="34">
    <Customer CustomerID="1" Fname="Jane" Lname="Miller" St1="23 abd st" City="Pittsburgh" State="PA" />
    <Customer CustomerID="2" Fname="Teddy" Lname="Billiam" St1="98 chd ave" City="California" State="CA" />
  </Product>
  <Product ProductID="3" ProductName="Swaddlers" Size="3" Price="36">
    <Customer CustomerID="3" Fname="Roy" Lname="Joyce" St1="34 bsst st" City="Chicago" State="MI" />
    <Customer CustomerID="7" Fname="Vickey" Lname="Derryl" St1="179 Forbes" City="Pittsburgh" State="CA" />
  </Product>
  <Product ProductID="5" ProductName="Swaddlers" Size="5" Price="34">
    <Customer CustomerID="2" Fname="Teddy" Lname="Billiam" St1="98 chd ave" City="California" State="CA" />
    <Customer CustomerID="4" Fname="Mike" Lname="Kerr" St1="3678 ALLE Ave" City="New York" State="NY" />
  </Product>
  <Product ProductID="10" ProductName="Cruisers" Size="5" Price="34">
    <Customer CustomerID="6" Fname="Lara" Lname="Kisa" St1="12 Larrence Ave" City="Seattle" State="WA" />
    <Customer CustomerID="7" Fname="Vickey" Lname="Derryl" St1="179 Forbes st" City="Pittsburgh" State="CA" />
  </Product>
</XOrder>
